In [2]:
import pandas as pd

df = pd.read_csv('result.csv')
df[['street', 'row']] = pd.DataFrame(df['Address'].str.split(',',1).tolist(),columns = ['street','row'])
df[['space','postal_code','city','district']] = pd.DataFrame(df['row'].str.split(' ', n=3, expand=True))
df[['street_clean','number']] = pd.DataFrame(df['street'].str.split(' ',1).tolist(),columns = ['street','row'])

# Adjustments in Flat size
df['Wohnflaeche'] = df['Wohnflaeche'].str.replace('m²', '')
df['Wohnflaeche'] = df['Wohnflaeche'].str.replace(' ', '')
df['Wohnflaeche'] = df['Wohnflaeche'].str.replace(',', '.')
df['Wohnflaeche'] = pd.to_numeric(df['Wohnflaeche'])
df.head(5)

,Title,Address,Wohnungstyp,Etage,Wohnflaeche,Bezugsfrei_ab,Zimmer,Schlafzimmer,Badezimmer,District,...,Kaution_o_genossenschaftsanteile,URL,street,row,space,postal_code,city,district,street_clean,number
0,Erstbezug nach sanierung - 2-Zimmer in toller ...,"Bürgerstr. 5, 12347 Berlin, Britz (Neukölln)",,2,75.73,sofort,2,,,,...,,http://www.immobilienscout24.de/expose/108763263,Bürgerstr. 5,"12347 Berlin, Britz (Neukölln)",,12347,"Berlin,",Britz (Neukölln),Bürgerstr.,5
1,"2-Zimmer-Wohnung im 10. OG, Sony Center","Bellevuestrasse 1, 10785 Berlin, Tiergarten (T...",,10 von 11,72.80,01.11.2018,2,,1,,...,,http://www.immobilienscout24.de/expose/107321332,Bellevuestrasse 1,"10785 Berlin, Tiergarten (Tiergarten)",,10785,"Berlin,",Tiergarten (Tiergarten),Bellevuestrasse,1
2,"Fast wie im Penthaus: Neubau mit Dachterrasse,...","Wassermannstraße 73, 12489 Berlin, Adlershof (...",,5 von 5,59.00,sofort,2,1,1,,...,,http://www.immobilienscout24.de/expose/107862035,Wassermannstraße 73,"12489 Berlin, Adlershof (Treptow)",,12489,"Berlin,",Adlershof (Treptow),Wassermannstraße,73
3,Helle 2-Zimmer-Wohnung in historischer Lage,"Karl-Marx-Allee 72, 10243 Berlin, Friedrichsha...",,4 von 7,67.86,01.12.2018,2,,,,...,,http://www.immobilienscout24.de/expose/94140698,Karl-Marx-Allee 72,"10243 Berlin, Friedrichshain (Friedrichshain)",,10243,"Berlin,",Friedrichshain (Friedrichshain),Karl-Marx-Allee,72
4,"Zweitwohnung in Berlin gesucht? · Exklusives, ...","Behrenstraße 28, 10117 Berlin, Mitte (Mitte)",,6 von 8,43.00,15.01.2019,1,,1,,...,,http://www.immobilienscout24.de/expose/108706138,Behrenstraße 28,"10117 Berlin, Mitte (Mitte)",,10117,"Berlin,",Mitte (Mitte),Behrenstraße,28